# 数値解析2020 レポート


**IX-B.**


以下Python3を用いたプログラム例を示す。

In [ ]:
# Pythonのバージョン確認
import sys
print(sys.version)

3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]


# 解答コード

In [ ]:
import numpy as np
import pandas as pd

x = np.array([111, 155, 146, 85, 216, 330, 225, 214])
y = np.array([112, 193, 104, 29, 237, 190, 210, 300])
z = np.array([ 96, 151, 114, 85, 186, 169, 210, 182])

data = pd.DataFrame(np.transpose(np.array([x,y,z])), columns=['h', 'a', 'd'])

print(data.corr())
A = np.array(data.corr())
print(A)

u = np.array([1,0,0])


for k in range(10):
    z = u/np.linalg.norm(u)
    u = A @ z
    l = np.dot(z, u)
    print(k, z, u, l)
    if np.linalg.norm(u - l * z) <= 10**-15:
        print(k, z, u, l)
        break
l1 = l
print(z, u, l1)

          h         a         d
h  1.000000  0.655902  0.764237
a  0.655902  1.000000  0.874182
d  0.764237  0.874182  1.000000
[[1.         0.6559015  0.76423727]
 [0.6559015  1.         0.87418232]
 [0.76423727 0.87418232 1.        ]]
0 [1. 0. 0.] [1.         0.6559015  0.76423727] 1.0
1 [0.7045984  0.46214715 0.53848036] [1.41924818 1.39502432 1.48096159] 2.44217524582853
2 [0.57212842 0.56236328 0.59700638] [1.39723786 1.45951559 1.52585628] 2.531123389541454
3 [0.55184578 0.57644267 0.60264424] [1.39049858 1.46522009 1.52830135] 2.532978164310431
4 [0.54895444 0.57845372 0.60335754] [1.38947142 1.46595825 1.528563  ] 2.533015513801849
5 [0.54854431 0.57874026 0.60345576] [1.38932429 1.46606165 1.52859827] 2.5330162657286666
6 [0.54848613 0.57878099 0.60346958] [1.38930339 1.4660763  1.52860323] 2.533016280867172
7 [0.54847788 0.57878677 0.60347154] [1.38930043 1.46607838 1.52860393] 2.533016281171956
8 [0.54847671 0.57878759 0.60347182] [1.38930001 1.46607868 1.52860403] 2.5330162

In [ ]:
x = np.array([111, 155, 146, 85, 216, 330, 225, 214])
y = np.array([112, 193, 104, 29, 237, 190, 210, 300])
z = np.array([ 96, 151, 114, 85, 186, 169, 210, 182])
print(sum(x), np.mean(x))
print(sum(y), np.mean(y))
print(sum(z), np.mean(z))

1482 185.25
1375 171.875
1193 149.125


In [ ]:
n = len(x)
print(np.var(x, ddof=1), np.var(y, ddof=1), np.var(z, ddof=1))
x_mean = np.mean(x)
y_mean = np.mean(y)
z_mean = np.mean(z)
sum_x = 0; sum2_x = 0
sum_y = 0; sum2_y = 0
sum_z = 0; sum2_z = 0
for i in range(n):
    sum_x += (x[i] - x_mean)**2; sum2_x += x[i]**2 - x_mean**2
    sum_y += (y[i] - y_mean)**2; sum2_y += y[i]**2 - y_mean**2
    sum_z += (z[i] - z_mean)**2; sum2_z += z[i]**2 - z_mean**2
print(sum_x/(n-1), sum_x/n, sum2_x/(n-1))
print(sum_y/(n-1), sum_y/n, sum2_y/(n-1))
print(sum_z/(n-1), sum_z/n, sum2_z/(n-1))

s_x = np.sqrt(np.var(x, ddof=1))
s_y = np.sqrt(np.var(y, ddof=1))
s_z = np.sqrt(np.var(z, ddof=1))

print(np.cov(x, y))
print(np.cov(y, z))
print(np.cov(z, x))

s_xy = (np.dot(x, y) - n*x_mean*y_mean)/(n-1)
s_yz = (np.dot(y, z) - n*y_mean*z_mean)/(n-1)
s_zx = (np.dot(z, x) - n*z_mean*x_mean)/(n-1)

print(s_xy, s_yz, s_zx)

6046.214285714285 7355.839285714285 2101.839285714286
6046.214285714285 5290.4375 6046.214285714285
7355.839285714285 6436.359375 7355.839285714285
2101.839285714286 1839.109375 2101.839285714286
[[6046.21428571 4374.17857143]
 [4374.17857143 7355.83928571]]
[[7355.83928571 3437.30357143]
 [3437.30357143 2101.83928571]]
[[2101.83928571 2724.39285714]
 [2724.39285714 6046.21428571]]
4374.178571428572 3437.3035714285716 2724.3928571428573


In [ ]:
print(s_xy / (s_x * s_y))
print(s_yz / (s_y * s_z))
print(s_zx / (s_z * s_x))

0.6559015016144638
0.8741823238222556
0.7642372690545298


# ↓ IX-B 解答表示用コード

In [ ]:
import numpy as np

n = 8

h = np.array([111, 155, 146, 85, 216, 330, 225, 214])
a = np.array([112, 193, 104, 29, 237, 190, 210, 300])
d = np.array([ 96, 151, 114, 85, 186, 169, 210, 182])

h_ave = 0
a_ave = 0
d_ave = 0
for i in range(n):
    h_ave += h[i]
    a_ave += a[i]
    d_ave += d[i]
h_ave = h_ave / n
a_ave = a_ave / n
d_ave = d_ave / n

#print(h_ave, a_ave, d_ave)

s_h = 0
s_a = 0
s_d = 0
for i in range(n):
    s_h += h[i]**2
    s_a += a[i]**2
    s_d += d[i]**2
s_h = np.sqrt((s_h - n*h_ave**2) / (n-1))
s_a = np.sqrt((s_a - n*a_ave**2) / (n-1))
s_d = np.sqrt((s_d - n*d_ave**2) / (n-1))

s2_ha = 0
s2_ad = 0
s2_dh = 0
for i in range(n):
    s2_ha += h[i] * a[i]
    s2_ad += a[i] * d[i]
    s2_dh += d[i] * h[i]
s2_ha = (s2_ha - n*h_ave*a_ave) / (n-1)
s2_ad = (s2_ad - n*a_ave*d_ave) / (n-1)
s2_dh = (s2_dh - n*d_ave*h_ave) / (n-1)

print(s2_ha, s2_ad, s2_dh)

A = np.array([
    [1, s2_ha/(s_h * s_a), s2_dh/(s_d * s_h)],
    [s2_ha/(s_h * s_a), 1, s2_ad/(s_a * s_d)],
    [s2_dh/(s_d * s_h), s2_ad/(s_a * s_d), 1]])

print(A)


u = np.array([1.0,0.0,0.0])
y = np.array([1.0,0.0,0.0])
m = 3

for k in range(100):
    norm = 0
    for i in range(m):
        norm += u[i]**2
    norm = np.sqrt(norm)

    for i in range(m):
        y[i] = u[i] / norm

    for i in range(m):
        u[i] = 0
        for j in range(m):
            u[i] += A[i][j] * y[j]
    eigen_val = 0
    
    for i in range(m):
        eigen_val += y[i] * u[i]
    print(k, y, u, eigen_val)
    residue = 0
    for i in range(m):
        residue += (u[i] - eigen_val * y[i])**2
    residue = np.sqrt(residue)
    if residue <= 10**-15:
        break



4374.178571428572 3437.3035714285716 2724.3928571428573
[[1.         0.6559015  0.76423727]
 [0.6559015  1.         0.87418232]
 [0.76423727 0.87418232 1.        ]]
0 [1. 0. 0.] [1.         0.6559015  0.76423727] 1.0
1 [0.7045984  0.46214715 0.53848036] [1.41924818 1.39502432 1.48096159] 2.44217524582853
2 [0.57212842 0.56236328 0.59700638] [1.39723786 1.45951559 1.52585628] 2.5311233895414547
3 [0.55184578 0.57644267 0.60264424] [1.39049858 1.46522009 1.52830135] 2.5329781643104314
4 [0.54895444 0.57845372 0.60335754] [1.38947142 1.46595825 1.528563  ] 2.5330155138018484
5 [0.54854431 0.57874026 0.60345576] [1.38932429 1.46606165 1.52859827] 2.5330162657286674
6 [0.54848613 0.57878099 0.60346958] [1.38930339 1.4660763  1.52860323] 2.5330162808671717
7 [0.54847788 0.57878677 0.60347154] [1.38930043 1.46607838 1.52860393] 2.533016281171957
8 [0.54847671 0.57878759 0.60347182] [1.38930001 1.46607868 1.52860403] 2.5330162811780927
9 [0.54847654 0.5787877  0.60347185] [1.38929995 1.4660787

# ↓ X-Aの解答

In [ ]:
import numpy as np
import pandas as pd

x = np.array([111, 155, 146, 85, 216, 330, 225, 214])
y = np.array([112, 193, 104, 29, 237, 190, 210, 300])
z = np.array([ 96, 151, 114, 85, 186, 169, 210, 182])


data = pd.DataFrame(np.transpose(np.array([x,y,z])), columns=['h', 'a', 'd'])

print(data.corr())
A = np.array(data.corr())
print(A)

u = np.array([1,0,0])

for s in reversed(range(200)):
    sigma = l1 * s / 200
    G = np.linalg.inv (sigma * np.eye(3) - A) 
    for k in range(10):
        z = u/np.linalg.norm(u)
        u = G @ z
        l = np.dot(z, u)
        #print(k, z, u, l)
        if np.linalg.norm(u - l * z) <= 10**-15:            
            print(k, z, u, sigma - 1/l )
            break
    #print(z, u, l)

          h         a         d
h  1.000000  0.655902  0.764237
a  0.655902  1.000000  0.874182
d  0.764237  0.874182  1.000000
[[1.         0.6559015  0.76423727]
 [0.6559015  1.         0.87418232]
 [0.76423727 0.87418232 1.        ]]
0 [0.54847651 0.57878772 0.60347186] [-7.21769953 -7.61658116 -7.94141311] 2.5330162811782184
1 [0.54847651 0.57878772 0.60347186] [-5.41327465 -5.71243587 -5.95605983] 2.5330162811782184
1 [0.54847651 0.57878772 0.60347186] [-4.33061972 -4.5699487  -4.76484787] 2.5330162811782184
0 [-0.54847651 -0.57878772 -0.60347186] [3.93692702 4.15449882 4.33167988] 2.5330162811782184
1 [-0.54847651 -0.57878772 -0.60347186] [3.60884976 3.80829058 3.97070656] 2.5330162811782184
0 [0.54847651 0.57878772 0.60347186] [-3.33124594 -3.51534515 -3.66526759] 2.5330162811782184
0 [-0.54847651 -0.57878772 -0.60347186] [3.0932998  3.26424907 3.40346276] 2.5330162811782184
2 [0.54847651 0.57878772 0.60347186] [-2.88707981 -3.04663246 -3.17656524] 2.5330162811782184
0 [-0.54847

# ↓X-Aの解答表示用コード

In [ ]:
import numpy as np
import copy

n = 8

h = np.array([111, 155, 146, 85, 216, 330, 225, 214])
a = np.array([112, 193, 104, 29, 237, 190, 210, 300])
d = np.array([ 96, 151, 114, 85, 186, 169, 210, 182])

h_ave = 0
a_ave = 0
d_ave = 0
for i in range(n):
    h_ave += h[i]
    a_ave += a[i]
    d_ave += d[i]
h_ave = h_ave / n
a_ave = a_ave / n
d_ave = d_ave / n

#print(h_ave, a_ave, d_ave)

s_h = 0
s_a = 0
s_d = 0
for i in range(n):
    s_h += h[i]**2
    s_a += a[i]**2
    s_d += d[i]**2
s_h = np.sqrt((s_h - n*h_ave**2) / (n-1))
s_a = np.sqrt((s_a - n*a_ave**2) / (n-1))
s_d = np.sqrt((s_d - n*d_ave**2) / (n-1))

s2_ha = 0
s2_ad = 0
s2_dh = 0
for i in range(n):
    s2_ha += h[i] * a[i]
    s2_ad += a[i] * d[i]
    s2_dh += d[i] * h[i]
s2_ha = (s2_ha - n*h_ave*a_ave) / (n-1)
s2_ad = (s2_ad - n*a_ave*d_ave) / (n-1)
s2_dh = (s2_dh - n*d_ave*h_ave) / (n-1)

print(s2_ha, s2_ad, s2_dh)

A = np.array([
    [1, s2_ha/(s_h * s_a), s2_dh/(s_d * s_h)],
    [s2_ha/(s_h * s_a), 1, s2_ad/(s_a * s_d)],
    [s2_dh/(s_d * s_h), s2_ad/(s_a * s_d), 1]])

print(A)

u = np.array([1.0, 0.0, 0.0])
y = np.array([0.0, 0.0, 0.0])
z = np.array([0.0, 0.0, 0.0])
L = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
M = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
m = 3

for s in reversed(range(200)):
    sigma = 2.5330162811782184 * s / 200
    B = copy.copy(-A)
    B[0][0] = sigma + B[0][0]
    B[1][1] = sigma + B[1][1]
    B[2][2] = sigma + B[2][2]
    for k in range(m):
        for i in range(k+1, m):
            M[i][k] = B[i][k]/B[k][k]
            B[i][k] = 0
            for j in range(k+1, m):
                B[i][j] = B[i][j] - M[i][k]*B[k][j]
            L[i][k] = M[i][k]

    for k in range(200):
        norm = 0
        for i in range(m):
            norm += u[i]**2
        norm = np.sqrt(norm)

        for i in range(m):
            y[i] = u[i] / norm

        # Forward substitution
        z[0] = y[0]
        for i in range(1, m): # 1, 2, ..., m-1
            sum = 0
            for j in range(i): # 0, ... , i-1
                sum += L[i][j] * z[j] 
            z[i] = y[i] - sum

        # Backward substitution
        u[m-1] = z[m-1] / B[m-1][m-1]
        for i in range(m-2, -1, -1):
            sum = 0
            for j in range(i+1,m):
                sum += B[i][j] * u[j]
            u[i] = (z[i] - sum) / B[i][i]
        eigen_val = 0        
        for i in range(m):
            eigen_val += y[i] * u[i]
        residue = 0
        for i in range(m):
            residue += (u[i] - eigen_val * y[i])**2
        residue = np.sqrt(residue)
        if residue <= 10**-15:
            print("s", s, "k", k, y, u, sigma - 1/eigen_val)
            break


4374.178571428572 3437.3035714285716 2724.3928571428573
[[1.         0.6559015  0.76423727]
 [0.6559015  1.         0.87418232]
 [0.76423727 0.87418232 1.        ]]
s 198 k 1 [-0.54847651 -0.57878772 -0.60347186] [21.65309859 22.84974348 23.82423933] 2.533016281178219
s 191 k 1 [-0.54847651 -0.57878772 -0.60347186] [4.81179969 5.07772077 5.29427541] 2.5330162811782184
s 190 k 0 [0.54847651 0.57878772 0.60347186] [-4.33061972 -4.5699487  -4.76484787] 2.533016281178219
s 189 k 1 [0.54847651 0.57878772 0.60347186] [-3.93692702 -4.15449882 -4.33167988] 2.533016281178219
s 188 k 0 [-0.54847651 -0.57878772 -0.60347186] [3.60884976 3.80829058 3.97070656] 2.533016281178219
s 187 k 0 [0.54847651 0.57878772 0.60347186] [-3.33124594 -3.51534515 -3.66526759] 2.533016281178219
s 186 k 2 [-0.54847651 -0.57878772 -0.60347186] [3.0932998  3.26424907 3.40346276] 2.533016281178219
s 185 k 0 [0.54847651 0.57878772 0.60347186] [-2.88707981 -3.04663246 -3.17656524] 2.533016281178219
s 184 k 1 [0.54847651 0

In [ ]:
print(A)
G = A
print(G)

[[1.         0.6559015  0.76423727]
 [0.6559015  1.         0.87418232]
 [0.76423727 0.87418232 1.        ]]
[[1.         0.6559015  0.76423727]
 [0.6559015  1.         0.87418232]
 [0.76423727 0.87418232 1.        ]]


# ↓試行錯誤の後

In [ ]:
import numpy as np

x = np.array([111, 155, 146, 85, 216, 330, 225, 214])
y = np.array([112, 193, 104, 29, 237, 190, 210, 300])
z = np.array([ 96, 151, 114, 85, 186, 169, 210, 182])

m = len(x)

A = np.corrcoef(x,y)
B = np.corrcoef(y,z)
C = np.corrcoef(z,x)
print(A)
print(B)
print(C)


[[1.        0.6559015]
 [0.6559015 1.       ]]
[[1.         0.87418232]
 [0.87418232 1.        ]]
[[1.         0.76423727]
 [0.76423727 1.        ]]


'\nA = np.corrcoef(x,y,z)\nprint(A)\nu = np.array([1,0,0])\n\nfor k in range(10):\n    z = u/np.linalg.norm(u)\n    u = A @ z\n    l = np.dot(z, u)\n    print(k, z, u, l)\n    if np.linalg.norm(u - l * z) <= 10**-15:\n        print(k, z, u, l)\n        break\nprint(z, u, l)\n'